from rolepermissions.roles import AbstractUserRole


class Admin(AbstractUserRole):
    available_permissions = {
        'view_user': True,
        'add_user': True,
        'update_user': True,
        'delete_user': True,
        'view_role': True,
        'add_role': True,
        'update_role': True,
        'delete_role': True,
        'view_permission': True,
        'add_permission': True,
        'delete_permission': True,
        'view_team': True,
        'add_team': True,
        'update_team': True,
        'delete_team': True,
        'view_team_role': True,
        'add_team_role': True,
        'update_team_role': True,
        'delete_team_role': True,
        'add_project': True,
        'view_project': True,
        'update_project': True,
        'delete_project': True,
        'view_team_member': True,
        'add_team_member': True,
        'update_team_member': True,
        'delete_team_member': True,
        'view_task': True,
        'add_task': True,
        'update_task': True,
        'delete_task': True,
        'view_incidence': True,
        'add_incidence': True,
        'update_incidence': True,
        'delete_incidence': True,
        'view_comment': True,
        'add_comment': True,
        'update_comment': True,
        'delete_comment': True,
        'view_company': True,
        'add_company': True,
        'update_company': True,
        'delete_company': True,
        'view_project_team': True,
        'add_project_team': True,
        'update_project_team': True,
        'delete_project_team': True,
    }


class Manager(AbstractUserRole):
    available_permissions = {
        'view_user': True,
        'add_user': True,
        'update_user': True,
        'delete_user': True,
        'view_permission': True,
        'add_permission': True,
        'delete_permission': True,
        'view_team': True,
        'add_team': True,
        'update_team': True,
        'delete_team': True,
        'view_team_role': True,
        'add_team_role': True,
        'update_team_role': True,
        'delete_team_role': True,
        'add_project': True,
        'view_project': True,
        'update_project': True,
        'delete_project': True,
        'view_team_member': True,
        'add_team_member': True,
        'update_team_member': True,
        'delete_team_member': True,
        'view_task': True,
        'add_task': True,
        'update_task': True,
        'delete_task': True,
        'view_incidence': True,
        'add_incidence': True,
        'update_incidence': True,
        'delete_incidence': True,
        'view_comment': True,
        'add_comment': True,
        'update_comment': True,
        'delete_comment': True,
        'view_company': True,
        'view_project_team': True,
        'add_project_team': True,
        'update_project_team': True,
        'delete_project_team': True,
    }


class Worker(AbstractUserRole):
    available_permissions = {
        'view_user': True,
        'add_user': True,
        'update_user': True,
        'delete_user': True,
        'view_role': True,
        'view_permission': True,
        'view_teams': True,
        'view_team_roles': True,
        'view_project': True,
        'view_team_member': True,
        'view_task': True,
        'add_task': True,
        'update_task': True,
        'delete_task': True,
        'view_incidence': True,
        'add_incidence': True,
        'update_incidence': True,
        'delete_incidence': True,
        'view_comment': True,
        'add_comment': True,
        'update_comment': True,
        'delete_comment': True,
        'view_company': True,
        'view_project_team': True,
    }