# Generated by Django 4.0.6 on 2022-08-01 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_server', '0005_alter_project_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='team',
        ),
    ]
