# Generated by Django 4.0.6 on 2022-08-01 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_server', '0006_remove_project_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='end_date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
