# Generated by Django 4.0.6 on 2022-08-01 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_server', '0007_project_end_date_project_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='start_date',
        ),
    ]
