# Generated by Django 4.0.6 on 2022-08-01 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_server', '0009_project_end_date_project_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(default='2020-01-01'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(default='2020-01-01'),
        ),
    ]
