# Generated by Django 4.0.6 on 2022-08-01 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_server', '0012_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=500)),
                ('start_date', models.DateField(default='2020-01-01')),
                ('limit_date', models.DateField(default='2020-01-01')),
                ('hours', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('state', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(default=None, null=True)),
                ('informer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidence_informer', to='task_server.teammember')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidence_responsible', to='task_server.teammember')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_server.task')),
            ],
        ),
    ]
