# Generated by Django 4.0.6 on 2022-08-01 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_server', '0014_taskcomment_incidencecomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidencecomment',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='task_server.teammember'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskcomment',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='task_server.teammember'),
            preserve_default=False,
        ),
    ]
