# Generated by Django 4.0.6 on 2022-08-01 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_server', '0015_incidencecomment_user_taskcomment_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incidencecomment',
            old_name='user',
            new_name='teamMember',
        ),
        migrations.RenameField(
            model_name='taskcomment',
            old_name='user',
            new_name='teamMember',
        ),
    ]
