# Generated by Django 4.0.6 on 2022-08-02 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_server', '0016_rename_user_incidencecomment_teammember_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team_role',
            name='company',
        ),
        migrations.AddField(
            model_name='team_role',
            name='team',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='task_server.team'),
        ),
    ]
