# Generated by Django 4.0.6 on 2022-08-02 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_server', '0017_remove_team_role_company_team_role_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='company',
        ),
    ]
