# Generated by Django 4.0.6 on 2022-08-04 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_server', '0018_remove_teammember_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='informer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='informer', to='task_server.teammember'),
        ),
        migrations.AlterField(
            model_name='task',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsible', to='task_server.teammember'),
        ),
    ]
