# Generated by Django 4.0.6 on 2022-08-05 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_server', '0019_alter_task_informer_alter_task_responsible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='limit_date',
            field=models.DateField(default='2020-01-01', null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateField(default='2020-01-01', null=True),
        ),
    ]
