# Generated by Django 4.0.6 on 2022-08-05 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_server', '0020_alter_task_limit_date_alter_task_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='hours',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='points',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
