# Generated by Django 4.0.6 on 2022-08-08 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_server', '0021_alter_task_hours_alter_task_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
