# Generated by Django 4.0.6 on 2022-08-12 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_server', '0025_incidence_user_task_user_alter_incidence_informer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='state',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
